export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Home } from "./Home";
export { default as HotelSingle } from "./HotelSingle";
export { default as HotelBooking } from "./HotelBooking";
export { default as UserBooking } from "./UserBooking";
export { default as UserEdit } from "./UserEdit";
export { default as UserProfile } from "./UserProfile";
export { default as Missing } from "./Missing";
